### ISSUE TITLE
When UI login is disabled in settings, default UI does not show all panels & widgets

### ISSUE THREAD

**Issue by cpq** [cesanta/mongoose-wizard#14]
- [x] Make sure all panels and widgets are shown: essentially, ignore `rg` and `wg` attributes (read and write levels)
- [x] If UI login is disabled, hide the "User joe" +  logout button on the toolbar

**Comment by robertc2000** [comment]
Fixed

**Comment by cpq** [comment]
Awesome! PR please!

**Comment by robertc2000** [comment]
PR is ready to be reviewed!
