### ISSUE TITLE
Build failure (ESP32) - Mongoose now requires a mongoose_config.h

### ISSUE THREAD

**Issue by dvosully** [cesanta/mongoose-wizard#2]
Mongoose Library is now configured using a mongoose_config.h file. For some build platforms this file is not generated by the wizard, the definitions are still set in the CMakeLists.txt instead. This results in a build failure on the ESP32 platform.

Also seems to not be generated for the Windows and Linux/Mac/Unix targets (but not confirmed to cause a build failure)

For the ESP32 platform the Mongoose Wizard should:

- Generate a mongoose_config.h
- Remove the configuration definitions from CMakeLists.txt

**Comment by cpq** [comment]
Fixed, thank you
