### ISSUE TITLE
Labels displayed truncated early

### ISSUE THREAD

**Issue by dvosully** [cesanta/mongoose-wizard#20]
Labels on the dashboard get truncated when there is still adequate space for them to be fully displayed.

This can be seen in the below screenshot. It is more noticeable when the wizard is displayed on a smaller screen or the browser window is resized to be small, but even when running at full screen.

To duplicate, create a long label on a panel and resize your browser window and observe the behaviour.

As can be seen below, there is ample space for the 'MQTT username' label to occupy, but it is truncated to 'MQTT usern...'. The width of the label in the below example is set to 1/2. This can be observed on many other labels in the attached screenshot to varying degrees of severity.

This is visible both in the wizard builder, and in the resulting webpage. Screenshot below taken in Edge, behaviour in the running generated webpage also visible in Firefox.

![label_sizing](https://github.com/cesanta/mongoose-wizard/assets/96342636/e5a60473-e9f6-4848-939e-b2f1ec55d93d)

**Comment by cpq** [comment]
Fixed!
