### ISSUE TITLE
CSS and Formatting Tools do not change "Label" elements.

### ISSUE THREAD

**Issue by tandrewspoe** [cesanta/mongoose-wizard#21]
For some reason the CSS doesn't seem to affect the "Label" device.  For example, I created this header, but I can't get any change to the Label CSS.  It affects the "Text" variabls, but not the "Label"
![Label Issue 1](https://github.com/cesanta/mongoose-wizard/assets/72472886/22b9e728-5df0-4431-ab5a-8a36f6b8f1da)
I also seem unable to adjust the Label alignment other than through the extra CSS.
![Label Issue 2](https://github.com/cesanta/mongoose-wizard/assets/72472886/2787393a-89ff-41ab-9f31-03220b6c91d8)

**Comment by cpq** [comment]
That's fixed with the recent updates
