### ISSUE TITLE
Wizard file upload not terminating

### ISSUE THREAD

**Issue by dvosully** [cesanta/mongoose-wizard#23]
A recent update to add an alignment to file writes has meant file uploads may not complete successfully.
Identified when trying to do an OTA firmware update which never completed, tracing revealed that in handle_uploads() the `us->received` never reached the `us->expected` when the file finished transmission, and the `close_uploaded_file()` callback was never executed.
Changing the `alignment` variable to 1 instead of 32 has stopped this fault from manifesting for me, but obviously that removes the point of the alignment for targets that require it.

**Comment by cpq** [comment]
Fixed, please verify!

Note that the new wizard is pushed.
The old wizard is accessible at https://mongoose.ws/wizard1/ - we'll keep that URL for some transition time

**Comment by dvosully** [comment]
I can confirm that this is no longer happening for me using the new wizard.

The old wizard is giving auth failure for data points when I log in currently, the changes there are quite substantial so I haven't investigated or tested with the old wizard.
