### ISSUE TITLE
Data glue discussion

### ISSUE THREAD

**Issue by cpq** [cesanta/mongoose-wizard#25]
@dvosully here I'd like to discuss your suggestion w.r.t. data glue.

Let me summarize briefly. You'd like to move from this:

```c
struct data s_data = {1, 2, "hi"};
struct data * glue_get_data(void) {
  return &s_data;
}
```

To this:

```c
void glue_get_data(struct data* mydata) {
  mydata->a = 1;
  mydata->b = 2;
  mydata->c = "hi";
}
```

I can see the following consequences:
- The suggested approach makes it a bit more obvious, populating structure members, hinting to a place where exactly "glueing" should happen. That I see as positive 
- This approach would make the setter function do nothing, so saving changes would not work by default, because we won't have a C structure in memory that holds current values. I see this as negative

@dvosully you have mentioned other points about memory saving, etc. I did not quite get those - could you elaborate please? Also maybe there are other benefits the suggested approach has, and maybe you have ideas how to make the default behavior with saving work, please?

**Comment by dvosully** [comment]
@cpq that summarises my proposed change to the API, but is not quite how I propose the generated code behave.

I propose that the wizard generated getter be as follows:
```
struct data s_data = {1, 2, "hi"};
void glue_get_data(struct data* mydata) {
  *mydata = s_data;
}
```

The above code still contains the static copy of s_data, and the setter can set this as it presently does. As I see it, this neutralises both of your above points about consequences. The setter still functions, and the getter still doesn't show struct members. At a casual glance, this behave much the same as the current code.

The difference is that when I populate the glue in my own application, I would remove that copy of s_data, 
dynamically populating the provided struct by modifying the getter to be as follows:

```
void glue_get_data(struct data* mydata) {
  mydata->a = 1;
  mydata->b = 2;
  mydata->c = "hi";
}
```

Note that the above is not what I suggest the wizard generate, but instead is how _I_ would use the modified wizard. For me, the advantage of this is the RAM saving as I would no longer be required to keep a static copy of s_data in RAM which I don't use elsewhere, when the master copy of this data already exists elsewhere. I would get and set the data struct dynamically from my master copy.

With the current getter API, it is not possible for me to save RAM by removeing the copy of s_data, as I must return a pointer to a copy of the struct. (If I'm wrong about that and there is a way to use stack memory to do this safely I would love to hear!)

Does this articulate my proposal better?

**Comment by cpq** [comment]
@dvosully Yes that's very clear, thank you! And it makes sense. I think we'll do it.

Just curious, how large are those structures in your case?
What's the average free RAM watermark you firmware operates on ?

FYI - this requested change is implemented & pushed, you can try it out.

**Comment by dvosully** [comment]
My average free RAM watermark is about 15kB. If I enable some additional capabilities then I sit around 3kB (if I have enough at all). There's a fair bit going on, I'm processing 48kSps audio and doing processing on that including filters, audio compression and FFTs.

The config data in my case contains numerous large strings, between 64-140 bytes each for URLs, passwords, usernames etc. It's not that I can't afford a few hundred bytes as much as I'm at the point where every byte counts.

Thanks, will try that and other recent changes out tomorrow.

**Comment by cpq** [comment]
@dvosully oh, 15kb. From our experience, when the free RAM on ESPs is below 10k, it goes unstable because of fragmentation. Anyways I can see the reason behind the optimisation.
Maybe there is a possibility to squeeze more bytes by using mongoose's built-in TLS, and avoiding mbedTLS alltogether - chances are it'll eat less RAM and can free up a couple of dozen kb.

**Comment by dvosully** [comment]
That's interesting to know you have had issues with fragmentation leading to stability issues around that threshold, I'll keep an eye on that.

I've been extremely deliberate with primarily using static or one time RAM allocation, almost all of that 15kB tends to be a contiguous block, so I think fragmentation is not yet causing me problems.

I'll investigate using the mongoose TLS soon, if it can save that much memory I'll be very happy!

**Comment by dvosully** [comment]
@cpq I've tested the latest changes with the get API change and it is working well for me.
Thanks for making the change.
