### ISSUE TITLE
Mongoose library files not generated by wizard for ESP32 platform

### ISSUE THREAD

**Issue by dvosully** [cesanta/mongoose-wizard#26]
When the 'Code' tab of the mongoose wizard is opened and the target is set to ESP32, main/mongoose.c and main/mongoose.h are not populated correctly. They contain 'Not found' as shown below.

![mongoose_c_not_found](https://github.com/user-attachments/assets/4ca4513e-b1f6-41b9-bed1-b95d7f2a3e87)

The other targets appear to correctly generate mongoose.c and mongoose.h

**Comment by cpq** [comment]
Fixed
