### ISSUE TITLE
Gauge widget configuration unclear

### ISSUE THREAD

**Issue by dvosully** [cesanta/mongoose-wizard#3]
When creating a gauge widget, its configuration is unclear. There are also some bugs in the creation of a new gauge widget.

- There are three configuration fields (min, max, color), but the help text is mostly not visible due to the size of the input fields (See attached picture). Min and Max are fairly easy to guess, but color is not without inspecting the json. Increasing the width of these fields would make it much more evident how this widget should be configured. See image below.
- The min and max fields of a new gauge are ignored when entered. The resulting gauge has a scale of 0 - 100 no matter what is entered.
- The color field doesn't change the color - the gauge is orange no matter what color is entered.
- If the color field is left blank, the gauge portion of the widget vanishes (becomes white?). Applying a different default color when the color field is blank would help this be less confusing.

![mg_wizard_01](https://github.com/cesanta/mongoose-wizard/assets/96342636/4fcf2e53-4c26-43dc-943d-a6ea8a55f680)

**Comment by cpq** [comment]
Fixed, thank you!
