### ISSUE TITLE
Element alignment and sizing problems

### ISSUE THREAD

**Issue by dvosully** [cesanta/mongoose-wizard#4]
The sizing and alignment of input types in the wizard is not yet very good.
Now that the size of an element can be set to a fraction of the full width of a panel, I would expect that an 'input' style field would expand to occupy the full space allocated to it.

See below example: Log level, Device name, Device ID and LED 1 are set to 1/2 size. MQTT URI label is set to 1/4 and input set to 3/4 size. The input field is required to enter a long URI, but is not any longer than the Device name/device ID fields which have a smaller space allocated to them. Note that this is more visible if a panel is created quite wide.

Also, the alignment of the input fields to 'center' causes them to be offset and ragged with respect to each other. I would expect the input elements be 'left' aligned in the space allocated to them so they line up better.

Picture shown in the wizard, but the behaviour is the same in the generated UI.

![mg_wizard_02](https://github.com/cesanta/mongoose-wizard/assets/96342636/c4e03e90-d4a6-47b0-84bd-ec0dc032b308)

**Comment by cpq** [comment]
Is this still an issue?

**Comment by dvosully** [comment]
No, no longer an issue. The new options have cleaned the alignment up nicely.
