### ISSUE TITLE
When an action/button is placed on a panel which has a save button, clicking the 'save' button triggers the action. I believe the button should only be triggered if it is clicked or otherwise explicitly activated.

### ISSUE THREAD

**Issue by cpq** [cesanta/mongoose-wizard#6]

**Comment by cpq** [comment]
@dvosully these two - an action button, and a save button, seem conflicting to me.. What would be an example of such setup?

**Comment by dvosully** [comment]
The situation I encountered it was: a panel to set the MQTT settings, with URL and authentication parameters, including user supplied certificate/key files to be uploaded. The user certificates could be deleted using an action button.

I was grouping settings into panels by functionality, thus had the certificate delete (action) and upload (file) on the same panel (with save enabled) as the URL set and other MQTT related parameters. The result of this arrangement was that clicking save on this panel would execute the action and delete the certificate.

I agree that save is conceptually conflicting with an action, this is why I didn't expect the save to trigger the action. My expectation was that an action would be executed only if the button is clicked, and would be ignored if save was executed on the panel.

It's easy enough to work around, split it into separate panels, but I found the behaviour unexpected enough to be worth mentioning.

**Comment by cpq** [comment]
Can't reproduce this one. I did the following steps:

1. Made blank UI
2.  Created 1 action variable
3. Created one panel with 1 "button" widget, attached to the action variable

<img width="691" alt="image" src="https://github.com/cesanta/mongoose-wizard/assets/601816/0de3035a-b0c5-4eb8-88d3-d1287b989c84">

4. Generated UI, clicked on "save" button - and nothing happens, action is NOT triggered
5. Clicked on the action button - action IS triggered.
6. Added an input widget to the panel. Save works as expected, input is triggered but action is not.

@dvosully could you double-check and elaborate on a correct way to reproduce, please?

**Comment by dvosully** [comment]
You beat me to it by seconds. This appears to be resolved in the current version. Save does not trigger an action (any more).

**Comment by cpq** [comment]
Thanks David! I am closing this one then.
