### ISSUE TITLE
Uploading a file to a file variable endpoint when not authenticated causes the application to crash in mongoose_impl.c handle_uploads(). To duplicate: create and place a file variable with a write auth level of 1, log in to the dashboard as user, restart the mongoose application, then try to upload a file using the (invalidated) user session open in the browser.

### ISSUE THREAD

**Issue by cpq** [cesanta/mongoose-wizard#9]

**Comment by robertc2000** [comment]
This seems to work for me. I did the steps as you mentioned and didn't manage to duplicate the issue...

**Comment by dvosully** [comment]
I (reporter) also cannot duplicate right now, though I did check and duplicate this morning...
Right now the file uploads are completely unauthenticated instead which would be why it's not crashing. I'm not sure exactly when that changed, except that it's behaving differently for me than it was earlier today.

**Comment by cpq** [comment]
Good, so I am closing this for now.

@robertc2000 please add relevant tests to make sure we never regress!
